site_name: NoFluxoUnB

repo_name: "2025-1-NoFluxoUNB"
repo_url: "https://github.com/unb-mds/2025-1-NoFluxoUNB"
site_url: https://unb-mds.github.io/2025-1-NoFluxoUNB/

theme:
  name: material
  language: "pt"
  logo: assets/grasshopper.svg
  favicon: assets/fav.png
  palette:
    scheme: slate
    primary: rose
    accent: blue
  features:
    - navigation.tabs
plugins:
  - search

nav:
  - Home: index.md
  - Planejamento:
    - Levantamento de Requisitos: planejamento/requisitos.md
    - Story Map: planejamento/storymap.md
    - Identidade visual: planejamento/idv.md
  
  - Ata de Reuniões: 
    - Reunião 1 - 27-29/03/2025: atas/27-29-03-25.md
    - Reunião 2 - 04/04/2025: atas/04-04-25.md
    - Reunião 3 - 08/04/2025: atas/08-04-25.md
    - Reunião 4 - 15/04/2025: atas/15-04-25.md
    - Reunião 5 - 17/04/2025: atas/17-04-25.md
    - Reunião 6 - 22/04/2025: atas/22-04-25.md
    - Reunião 7 - 24/04/2025: atas/24-04-25.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unb-mds/2025-1-NoFluxoUNB
