site_name: NoFluxoUnB

repo_name: NoFluxoUNB
repo_url: https://github.com/unb-mds/2025-1-NoFluxoUNB
site_url: https://unb-mds.github.io/2025-1-NoFluxoUNB
site_description: Documentação oficial do NoFluxoUnB - Plataforma de planejamento acadêmico da UnB/FGA
site_author: Squad 03 - MDS/FGA/UnB

theme:
  name: material
  logo: assets/images/favicon-unb.png
  favicon: assets/images/favicon-unb.png
  palette:
    primary: #005DFF
    accent: #D3D3D3
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Estrutura da Documentação:
    - Requisitos: estrutura/requisitos.md
    - Story Map: estrutura/storymap.md
  - Ata de Reuniões:
    - 04-04-25: atas/04-04-25.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
